// Content gate: run after `astro build`. Fails on banned strings, broken
// internal links, or unparseable data files.
import { readdirSync, readFileSync, statSync, existsSync } from 'node:fs';
import { join, extname } from 'node:path';

const DIST = 'dist';
const DATA = 'src/data';
const BASE = '/all-about-dllms';

const failures = [];

// 1. all data JSON parses
for (const f of readdirSync(DATA)) {
  if (extname(f) !== '.json') continue;
  try {
    JSON.parse(readFileSync(join(DATA, f), 'utf8'));
  } catch (e) {
    failures.push(`JSON parse: ${f}: ${e.message}`);
  }
}
const trajDir = join(DATA, 'trajectories');
if (existsSync(trajDir)) {
  for (const f of readdirSync(trajDir)) {
    if (extname(f) !== '.json') continue;
    try {
      const t = JSON.parse(readFileSync(join(trajDir, f), 'utf8'));
      if (!Array.isArray(t.steps) || t.steps.length === 0)
        failures.push(`trajectory ${f}: empty steps`);
    } catch (e) {
      failures.push(`JSON parse: trajectories/${f}: ${e.message}`);
    }
  }
}

// 2. walk dist html
function* walk(dir) {
  for (const entry of readdirSync(dir)) {
    const p = join(dir, entry);
    if (statSync(p).isDirectory()) yield* walk(p);
    else yield p;
  }
}

const banned = [
  { re: /—/g, name: 'em-dash' },
  { re: /Generated by/gi, name: '"Generated by"' },
  { re: /\b(leverage|unlock)\b/gi, name: 'banned word' },
];

const htmlFiles = [];
if (!existsSync(DIST)) {
  failures.push('dist/ missing; run `npm run build` first');
} else {
  for (const p of walk(DIST)) {
    if (extname(p) === '.html') htmlFiles.push(p);
  }
  for (const p of htmlFiles) {
    const html = readFileSync(p, 'utf8');
    // strip katex MathML (contains U+2014 in some operator tables? keep strict anyway)
    for (const b of banned) {
      const m = html.match(b.re);
      if (m) failures.push(`${b.name} x${m.length} in ${p}`);
    }
    // internal links
    for (const m of html.matchAll(/href="([^"#]+)(#[^"]*)?"/g)) {
      const href = m[1];
      if (/^(https?:|mailto:|data:)/.test(href)) continue;
      let target = href.startsWith(BASE) ? href.slice(BASE.length) : href;
      if (!target.startsWith('/')) continue; // relative links resolved by astro
      if (target === '/' || target === '') target = '/index.html';
      let fsPath = join(DIST, target);
      const candidates = [fsPath, join(fsPath, 'index.html')];
      if (!candidates.some((c) => existsSync(c))) {
        failures.push(`broken internal link ${href} in ${p}`);
      }
    }
  }
}

if (failures.length) {
  console.error(`CHECK FAILED (${failures.length}):`);
  for (const f of failures) console.error('  - ' + f);
  process.exit(1);
}
console.log(`check ok: ${htmlFiles.length} pages, data valid, links resolve.`);
